### ISSUE TITLE
MQTT documentation precisions

### ISSUE THREAD

**Issue by nicolascrochet7** [lee-orr/spin-message-trigger#17]
Hi @lee-orr,

First of all, thank you for including MQTT in your Spin plugin, it opens up great use cases.

I haven't had the chance and the time to use it yet, but I went through the documentation, and I am not sure that I am grasping everything right.

The documentation mentions an MQTT broker trigger, but from my overview, the spin trigger is an MQTT client and the broker would be required at the address mqtt://mqtt:1883. Is that right ?

If so, how do we perform the initial CONNECT message with username and password to the broker ?

(Sorry if I am off track, Spin and Rust are still quite new to me.)

**Comment by lee-orr** [comment]
Yes - the spin trigger acts as a client, and you would replace the address I provided with the actual address of your broker. 

The connection process gets abstracted away by the broker, so you don't need to manually issue a connect message. In the initial design, I did overlook setting a username & password - so I'm adding that in ATM. It'll be part of the configuration options for the trigger. I'll update here when it's done.

**Comment by lee-orr** [comment]
The most recent version should support username & password.

Do you have any other questions, is this a bit clearer?

**Comment by lee-orr** [comment]
@nicolascrochet7 - since I haven't heard from you in the last few weeks, I'm going to close this issue. Feel free to re-open it if you don't feel it's been resolved

**Comment by nicolascrochet7** [comment]
Sorry for the delay I didn't see your messages, thank you for adding username and password !
